// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// png_to_escpos_raster
std::string png_to_escpos_raster(std::string png_path, std::string raster_path);
RcppExport SEXP _ggpos_png_to_escpos_raster(SEXP png_pathSEXP, SEXP raster_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type png_path(png_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type raster_path(raster_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(png_to_escpos_raster(png_path, raster_path));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ggpos_png_to_escpos_raster", (DL_FUNC) &_ggpos_png_to_escpos_raster, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ggpos(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
