# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
png_to_escpos_raster <- function(png_path, raster_path) {
    .Call(`_ggpos_png_to_escpos_raster`, png_path, raster_path)
}

